version: "2.4"

services:
  couchdb-0:
    restart: always
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      NODENAME: couchdb-0.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-0.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}0:5984"
    volumes:
      - "data-couch-0:/opt/couchdb/data"
      - "cfg-couch-0:/opt/couchdb/etc/local.d"
  couchdb-1:
    restart: always
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      NODENAME: couchdb-1.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-1.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}1:5984"
    volumes:
      - "data-couch-1:/opt/couchdb/data"
      - "cfg-couch-1:/opt/couchdb/etc/local.d"
  couchdb-2:
    restart: always
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_SECRET: ${COUCHDB_SECRET}
      NODENAME: couchdb-2.${COMPOSE_PROJECT_NAME}
      ERL_FLAGS: "-setcookie ${COUCHDB_COOKIE}"
    image: couchdb:3
    networks:
      network:
        aliases:
          - couchdb-2.${COMPOSE_PROJECT_NAME}
    ports:
      - "${PORT_BASE}2:5984"
    volumes:
      - "data-couch-2:/opt/couchdb/data"
      - "cfg-couch-2:/opt/couchdb/etc/local.d"

  nginx:
    image: nginx
    ports:
      - "5984:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      network:
        aliases:
          - nginx

  clouseau-0:
    image: openjdk:8
    command: >
      java -server -classpath '/app/*' -Xmx2G -Dsun.net.inetaddr.ttl=30 -Dsun.net.inetaddr.negative.ttl=30 -Dlog4j.configuration=file:/config/log4j.properties -XX:OnOutOfMemoryError="kill -9 %p" -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled com.cloudant.clouseau.Main /config/clouseau.ini
    restart: always
    depends_on:
      - couchdb-0
    volumes:
      - ./config/clouseau:/config
      - ./clouseau-2.21.0:/app
    network_mode: service:couchdb-0

  clouseau-1:
    image: openjdk:8
    command: >
      java -server -classpath '/app/*' -Xmx2G -Dsun.net.inetaddr.ttl=30 -Dsun.net.inetaddr.negative.ttl=30 -Dlog4j.configuration=file:/config/log4j.properties -XX:OnOutOfMemoryError="kill -9 %p" -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled com.cloudant.clouseau.Main /config/clouseau.ini
    restart: always
    depends_on:
      - couchdb-1
    volumes:
      - ./config/clouseau:/config
      - ./clouseau-2.21.0:/app
    network_mode: service:couchdb-1

  clouseau-2:
    image: openjdk:8
    command: >
      java -server -classpath '/app/*' -Xmx2G -Dsun.net.inetaddr.ttl=30 -Dsun.net.inetaddr.negative.ttl=30 -Dlog4j.configuration=file:/config/log4j.properties -XX:OnOutOfMemoryError="kill -9 %p" -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled com.cloudant.clouseau.Main /config/clouseau.ini
    restart: always
    depends_on:
      - couchdb-2
    volumes:
      - ./config/clouseau:/config
      - ./clouseau-2.21.0:/app
    network_mode: service:couchdb-2

  couch-forum:
    image: couch-forum
    ports: 
      - "3000:3000"
    networks:
      network:
        aliases:
          - couch-forum

networks:
  network:


volumes:
  data-couch-0:
  cfg-couch-0:
  data-couch-1:
  cfg-couch-1:
  data-couch-2:
  cfg-couch-2:
