import Head from 'next/head';
import { useRouter } from 'next/router';
import useSwr from 'swr';

const fetcher = (url) => fetch(url).then((r) => r.json())

export default function Home() {
  const { data, error } = useSwr(`api/hello/?name=Alvaro`, fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 >
          Welcome to an app writed by {data.name}
        </h1>
      </main>
    </div>
  )
}
